services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./packages/app
      dockerfile: Dockerfile
    container_name: logoexecutive-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./packages/app/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./packages/ui
      dockerfile: Dockerfile
    container_name: logoexecutive-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./packages/ui/.env
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
