services:
  mongodb:
    image: mongo:latest
    container_name: openlogo-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  express:
    build:
      context: ./packages/app
      dockerfile: Dockerfile
    container_name: openlogo-express
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./packages/app/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  react:
    build:
      context: ./packages/ui
      dockerfile: Dockerfile
    container_name: openlogo-react
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./packages/ui/.env
    depends_on:
      - express
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
